import { ProductType } from "../../types/types";

const initialState: ProductType[] = [
  {
    id: 0,
    title: "Apple iPhone 15 Pro",
    price: 1199.0,
    description: "iphone15pro",
    isFavorite: false,
    isStock: false,
  },
  {
    id: 1,
    title: "Apple Watch Series 8",
    price: 649.0,
    description: "applewatch8",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 2,
    title: "Apple AirPods 3",
    price: 199.0,
    description: "airpods3",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 3,
    title: "Apple iPhone XS Max",
    price: 339.0,
    description: "iphonexs",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 4,
    title: "Apple Watch Series 9",
    price: 899.0,
    description: "applewatch9",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 5,
    title: "Apple iPhone 15",
    price: 949.0,
    description: "iphone15",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 6,
    title: "Apple AirPods Pro 2",
    price: 279.0,
    description: "airpods2gen",
    isFavorite: false,
    isStock: false,
  },
  {
    id: 7,
    title: "Apple Watch Ultra 2",
    price: 869.0,
    description: "applewatchultra",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 8,
    title: "Apple iPhone 12 Pro",
    price: 649.0,
    description: "iphone12promax",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 9,
    title: "Samsung Watch 5",
    price: 299.0,
    description: "galaxywatch5",
    isFavorite: false,
    isStock: false,
  },
  {
    id: 10,
    title: "Apple iPhone 13 Pro",
    price: 799.0,
    description: "iphone13pro",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 11,
    title: "Samsung Galaxy Flip5",
    price: 829.0,
    description: "galaxyflip",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 12,
    title: "Apple iPhone 14 Plus",
    price: 979.0,
    description: "iphone14plus",
    isFavorite: false,
    isStock: false,
  },
  {
    id: 13,
    title: "Apple AirPods 2",
    price: 159.0,
    description: "airpods2",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 14,
    title: "Samsung Galaxy S23",
    price: 699.0,
    description: "samsungs23",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 15,
    title: "Apple Watch SE",
    price: 279.0,
    description: "applewatchse",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 16,
    title: "Jabra Elite 10",
    price: 199.0,
    description: "jabra",
    isFavorite: false,
    isStock: false,
  },
  {
    id: 17,
    title: "Amazfit GTS 4",
    price: 169.0,
    description: "amazfit",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 18,
    title: "Samsung Galaxy Fold5",
    price: 1349.0,
    description: "samsunggalaxyfold5",
    isFavorite: false,
    isStock: true,
  },
  {
    id: 19,
    title: "Huawei FreeBuds Pro 2",
    price: 194.0,
    description: "huaweifreebuds",
    isFavorite: false,
    isStock: true,
  },
];

const shopReducer = (state: ProductType[] = initialState, action: any) => {
  return state;
};

export const actions = {};

export type ShopType = typeof initialState;
export default shopReducer;
